version: '3.7'

services:
  backend:
    container_name: caller-id
    image: caller-id-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - mainnet
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    networks:
      - mainnet
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - POSTGRES_DB=caller-id
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mainnet
networks:
  mainnet:
volumes:
  pgdata:
