name: Build and Deploy - SamSung BE

on:
    push:
      branches:
        - main
      paths:
        - 'server/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: server
          file: server/dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/samsungbe:latest
            ${{ vars.DOCKERHUB_USERNAME }}/samsungbe:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-22.04
    needs: build-and-push-image
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_PROD }}
          username: ${{ vars.HOST_USERNAME }}
          password: ${{ secrets.PASS_WORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd samsung-energy-simulator
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/samsungbe:latest
            docker-compose down
            docker-compose up -d
