name: Build and Deploy - SamSung FE

on:
    push:
      branches:
        - main
      paths:
        - 'client/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: client
          file: client/dockerfile
          push: true
          tags:  |
            ${{ vars.DOCKERHUB_USERNAME }}/samsungfe:latest
            ${{ vars.DOCKERHUB_USERNAME }}/samsungfe:${{github.sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: Access server, pull new image and restart container
    runs-on: ubuntu-22.04
    needs: build-and-push-image
    steps:
      
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_PROD }}
          username: ${{ vars.HOST_USERNAME }}
          password: ${{ secrets.PASS_WORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd samsung-energy-simulator
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/samsungfe:latest
            docker-compose down
            docker-compose up -d